import { red } from '@mui/material/colors';
import Head from 'next/head'
import { useEffect,useState } from 'react';

export default function Home() {

    useEffect(() => {
        let cred = JSON.parse(localStorage.getItem('cred'));
        console.log(cred);
        if (cred) {
            if (cred.username == "Sharon@1" && cred.password == "Sharon@1") {
                console.log("logged in");
                window.location.href = "/admin"
            }
        }
    }, []);

    const [user, setUser] = useState("");
    const [password, setPassword] = useState("");

    const checker = () => {
        if (user == "Sharon@1" && password == "Sharon@1") {
            localStorage.setItem('cred', JSON.stringify({username: user, password: password}));
            window.location.href = "/admin"
        }
    }


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-black h-screen">
                <section class="bg-gray-50 dark:bg-gray-900">
                    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                        <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
                                SHARON INDUSTRIES
                        </a>
                        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                                    Sign in to your Admin
                                </h1>
                                <form class="space-y-4 md:space-y-6">
                                    <div>
                                        <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">username</label>
                                        <input type="text" value={user} onChange={(e) => setUser(e.target.value)} name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="username" required=""/>
                                    </div>
                                    <div>
                                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                                        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required=""/>
                                    </div>
                                    <button type="button" onClick={checker} class="w-full text-white bg-sharon-or focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm px-5 py-2.5 text-center ">Sign in</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>

            </main>
        </>
    )
}
