import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '../components/Navbar'
import { Card_keeper } from '../components/Card_keeper'
import { useState, useEffect, useRef } from "react";
import { db } from "../firebase";
import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
} from "firebase/firestore";
import { v4 } from "uuid";
import { useSelector, useDispatch } from 'react-redux'
import { addUrl, increment } from '../slice/counterSlice'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const dispatch = useDispatch()
  const imageUrls = useSelector((state) => state.home.home_url)
  const shouldlog = useRef(true);
  const productsRef = collection(db, "products");

  
  
      // const imagesListRef = ref(storage, "home");
      // listAll(imagesListRef).then((response) => {
      //   response.items.forEach((item) => {
      //     getDownloadURL(item).then((url) => {
      //       console.log(url);
      //       setImageUrls((prev) => [...prev, url]);
      //     });
      //   });
      // });


  useEffect(() => {
    if (shouldlog.current) {
      shouldlog.current = false;
      const getUsers = async () => {
        const urls = await getDocs(productsRef);
        urls.forEach((doc) => {
          dispatch(addUrl(doc.data()))
        })
      };

      getUsers();

    }
  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-screen">
        <Navbar />

        {/* PRODUCTS SECTION */}

        <div className="h-full w-screen bg-black p-8 ">

          <h1 className="text-4xl font-bold my-8 text-center">
            Our Products
          </h1>

          <Card_keeper imageUrls={imageUrls} />

        </div>
      </main>
    </>
  )
}
